### FIND ALL
GET http://localhost:3000/api/cuotasMensuales

###Generar todas las cuotas

POST http://localhost:3000/api/cuotasMensuales/generar



### ID
@id = 13

### GET ONE
GET http://localhost:3000/api/cuotasMensuales/{{id}}

### UPDATE Cuota mensual (El socio paga su cuota)
PUT http://localhost:3000/api/cuotasMensuales/{{id}}
Content-Type: application/json

{
  "pagada": true,
  "fechaPago": "2025-09-04"
}

### DELETE
DELETE http://localhost:3000/api/cuotasMensuales/13


### Listado de cuotas mensuales impagas por socio
@socioId = 1
GET http://localhost:3000/api/cuotasMensuales/impagas/{{socioId}}