### Obtener todos los boxes
GET http://localhost:3000/api/boxes

### Obtener un box por id
GET http://localhost:3000/api/boxes/{{id}}


###ID
@id = {{createBox.response.body.data.id}}

### POST
# @name createBox
POST http://localhost:3000/api/boxes
Content-Type: application/json

{ "nroBox": "B001",
  "estado": "disponible",
  "precioMensualBase": 1500
}

### Actualizar un box existente
PUT http://localhost:3000/api/boxes/1
Content-Type: application/json

{
  "embarcacion": 2
}



### POST BOX TO DELETE
# @name createBoxToDelete
POST http://localhost:3000/api/boxes
Content-Type: application/json

{
  "estado": "disponible",
  "precioMensualBase": 1500,
  "nroBox": "B002"
}


### Eliminar un box
@idToDelete = {{createBoxToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/boxes/{{idToDelete}}
